# Generated by Django 4.2.4 on 2026-03-10 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('survey_in_progress', 'Survey In Progress'), ('submitted_to_land_office', 'Submitted to Land Office'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customers.customer')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Project',
                'verbose_name_plural': 'Survey Projects',
                'db_table': 'survey_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('survey_in_progress', 'Survey In Progress'), ('submitted_to_land_office', 'Submitted to Land Office'), ('completed', 'Completed')], max_length=50)),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.surveyproject')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Update',
                'verbose_name_plural': 'Project Updates',
                'db_table': 'project_updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LandTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('survey_map', 'Survey Map'), ('land_title', 'Land Title'), ('boundary_report', 'Boundary Report')], max_length=50)),
                ('document_file', models.FileField(upload_to='land_titles/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.surveyproject')),
            ],
            options={
                'verbose_name': 'Land Title Document',
                'verbose_name_plural': 'Land Title Documents',
                'db_table': 'land_titles',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
