# Generated by Django 4.2.4 on 2026-03-21 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_type', models.CharField(choices=[('survey_start', 'Survey Start'), ('survey_completion', 'Survey Completion'), ('document_submission', 'Document Submission'), ('land_office_response', 'Land Office Response'), ('final_completion', 'Final Completion'), ('custom', 'Custom Milestone')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_days_before', models.IntegerField(default=3)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Deadline',
                'verbose_name_plural': 'Project Deadlines',
                'db_table': 'project_deadlines',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='enable_reminders',
            field=models.BooleanField(default=True, help_text='Enable automatic reminders for this project'),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='expected_completion_date',
            field=models.DateField(blank=True, help_text='Expected date for final completion', null=True),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='land_office_processing_days',
            field=models.IntegerField(default=30, help_text='Expected days for land office processing'),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='land_office_submission_date',
            field=models.DateField(blank=True, help_text='When documents were submitted to land office', null=True),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='reminder_days_before',
            field=models.IntegerField(default=3, help_text='Days before deadline to send reminders'),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='scheduled_end_date',
            field=models.DateField(blank=True, help_text='When the survey work should be completed', null=True),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='scheduled_start_date',
            field=models.DateField(blank=True, help_text='When the survey work is scheduled to begin', null=True),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='survey_duration_days',
            field=models.IntegerField(default=7, help_text='Expected days to complete survey work'),
        ),
        migrations.CreateModel(
            name='ProjectReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('deadline_approaching', 'Deadline Approaching'), ('overdue', 'Overdue'), ('status_update_required', 'Status Update Required'), ('document_required', 'Document Required'), ('custom', 'Custom Reminder')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_in_app', models.BooleanField(default=True)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('in_app_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='projects.projectdeadline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='projects.surveyproject')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Reminder',
                'verbose_name_plural': 'Project Reminders',
                'db_table': 'project_reminders',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='projects.surveyproject'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='related_deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectdeadline'),
        ),
    ]
