# Generated by Django 4.2.4 on 2026-03-23 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_projectdeadline_surveyproject_enable_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyproject',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='completion_notes',
            field=models.TextField(blank=True, default='', help_text='Notes added when marking project complete'),
        ),
    ]
