# Generated by Django 4.2.4 on 2026-03-26 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('project_assigned', 'Project Assigned'), ('project_claimed', 'Project Claimed'), ('project_status', 'Project Status Changed'), ('project_completed', 'Project Completed'), ('project_overdue', 'Project Overdue'), ('new_project', 'New Project Created'), ('new_property', 'New Property Added'), ('new_customer', 'New Customer Added'), ('new_expense', 'New Expense Recorded'), ('new_transaction', 'New Transaction'), ('general', 'General')], default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('property_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
